# Week 4 Assignment

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

In [22]:
nhl_df=pd.read_csv("nhl.csv")
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

In [3]:
nhl_df.head()

,team,GP,W,L,OL,PTS,PTS%,GF,GA,SRS,SOS,RPt%,ROW,year,League
0,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,2018,NHL
1,Tampa Bay Lightning*,82,54,23,5,113,.689,296,236,0.66,-0.07,.634,48,2018,NHL
2,Boston Bruins*,82,50,20,12,112,.683,270,214,0.62,-0.07,.610,47,2018,NHL
3,Toronto Maple Leafs*,82,49,26,7,105,.640,277,232,0.49,-0.06,.567,42,2018,NHL
4,Florida Panthers,82,44,30,8,96,.585,248,246,-0.01,-0.04,.537,41,2018,NHL

In [4]:
nhl_df.shape

(171, 15)

In [16]:
nhl_df.year.value_counts()

2017    68
2018    35
2015    34
2014    34
Name: year, dtype: int64

**Keeping only 2018 data**

In [19]:
nhl_df2018 = nhl_df[nhl_df.year == 2018]
nhl_df2018.head()

,team,GP,W,L,OL,PTS,PTS%,GF,GA,SRS,SOS,RPt%,ROW,year,League
0,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,2018,NHL
1,Tampa Bay Lightning*,82,54,23,5,113,.689,296,236,0.66,-0.07,.634,48,2018,NHL
2,Boston Bruins*,82,50,20,12,112,.683,270,214,0.62,-0.07,.610,47,2018,NHL
3,Toronto Maple Leafs*,82,49,26,7,105,.640,277,232,0.49,-0.06,.567,42,2018,NHL
4,Florida Panthers,82,44,30,8,96,.585,248,246,-0.01,-0.04,.537,41,2018,NHL

In [28]:
nhl_df2018.shape

(35, 15)

In [25]:
sorted(nhl_df2018.team)

['Anaheim Ducks*',
 'Arizona Coyotes',
 'Atlantic Division',
 'Boston Bruins*',
 'Buffalo Sabres',
 'Calgary Flames',
 'Carolina Hurricanes',
 'Central Division',
 'Chicago Blackhawks',
 'Colorado Avalanche*',
 'Columbus Blue Jackets*',
 'Dallas Stars',
 'Detroit Red Wings',
 'Edmonton Oilers',
 'Florida Panthers',
 'Los Angeles Kings*',
 'Metropolitan Division',
 'Minnesota Wild*',
 'Montreal Canadiens',
 'Nashville Predators*',
 'New Jersey Devils*',
 'New York Islanders',
 'New York Rangers',
 'Ottawa Senators',
 'Pacific Division',
 'Philadelphia Flyers*',
 'Pittsburgh Penguins*',
 'San Jose Sharks*',
 'St. Louis Blues',
 'Tampa Bay Lightning*',
 'Toronto Maple Leafs*',
 'Vancouver Canucks',
 'Vegas Golden Knights*',
 'Washington Capitals*',
 'Winnipeg Jets*']

In [27]:
cities.head()

,Metropolitan area,Population (2016 est.)[8],NFL,MLB,NBA,NHL
0,New York City,20153634,GiantsJets[note 1],YankeesMets[note 2],KnicksNets,RangersIslandersDevils[note 3]
1,Los Angeles,13310447,RamsChargers[note 4],DodgersAngels,LakersClippers,KingsDucks
2,San Francisco Bay Area,6657982,49ersRaiders[note 6],GiantsAthletics,Warriors,Sharks[note 7]
3,Chicago,9512999,Bears[note 8],CubsWhite Sox,Bulls[note 9],Blackhawks
4,Dallas–Fort Worth,7233323,Cowboys,Rangers,Mavericks,Stars

In [29]:
cities.shape

(51, 6)

In [139]:
sorted(cities.NHL)

['Avalanche[note 18]',
 'Blackhawks',
 'Blue Jackets',
 'Blues[note 43]',
 'Bruins',
 'Canadiens',
 'Canucks',
 'Capitals',
 'Coyotes',
 'Flames',
 'Flyers[note 13]',
 'Golden Knights',
 'Hurricanes',
 'Jets[note 61]',
 'KingsDucks',
 'Lightning',
 'Maple Leafs',
 'Oilers',
 'Panthers',
 'Penguins[note 28]',
 'Predators',
 'RangersIslandersDevils[note 3]',
 'Red Wings',
 'Sabres',
 'Senators',
 'Sharks[note 7]',
 'Stars',
 'Wild[note 16]',
 '[note 25]',
 '[note 32]',
 '[note 34]',
 '[note 39]',
 '[note 71]',
 '—',
 '—',
 '—',
 '—',
 '—',
 '—',
 '—',
 '—',
 '—',
 '—',
 '—',
 '—',
 '—',
 '—',
 '—',
 '—',
 '—',
 '—']

In [147]:
cities.NHL.replace("\[\w.*\]|—",'',regex=True).apply(lambda x: re.findall('[A-Z][^A-Z]*', x))

0     [Rangers, Islanders, Devils]
1                   [Kings, Ducks]
2                         [Sharks]
3                     [Blackhawks]
4                          [Stars]
5                       [Capitals]
6                         [Flyers]
7                         [Bruins]
8                           [Wild]
9                      [Avalanche]
10                      [Panthers]
11                       [Coyotes]
12                   [Red , Wings]
13                 [Maple , Leafs]
14                              []
15                              []
16                     [Lightning]
17                      [Penguins]
18                              []
19                              []
20                              []
21                              []
22                         [Blues]
23                              []
24                              []
25                              []
26                     [Predators]
27                              []
28                              []
29                        [Sabres]
30                     [Canadiens]
31                       [Canucks]
32                              []
33                              []
34                [Blue , Jackets]
35                        [Flames]
36                      [Senators]
37                        [Oilers]
38                              []
39                          [Jets]
40                              []
41                              []
42                              []
43              [Golden , Knights]
44                              []
45                              []
46                              []
47                    [Hurricanes]
48                              []
49                              []
50                              []
Name: NHL, dtype: object

In [46]:
cities.NHL.apply(lambda x: re.findall('[A-Z][^A-Z]*', x))#.str[0]

0     [Rangers, Islanders, Devils[note 3]]
1                           [Kings, Ducks]
2                         [Sharks[note 7]]
3                             [Blackhawks]
4                                  [Stars]
5                               [Capitals]
6                        [Flyers[note 13]]
7                                 [Bruins]
8                          [Wild[note 16]]
9                     [Avalanche[note 18]]
10                              [Panthers]
11                               [Coyotes]
12                           [Red , Wings]
13                         [Maple , Leafs]
14                                      []
15                                      []
16                             [Lightning]
17                     [Penguins[note 28]]
18                                      []
19                                      []
20                                      []
21                                      []
22                        [Blues[note 43]]
23                                      []
24                                      []
25                                      []
26                             [Predators]
27                                      []
28                                      []
29                                [Sabres]
30                             [Canadiens]
31                               [Canucks]
32                                      []
33                                      []
34                        [Blue , Jackets]
35                                [Flames]
36                              [Senators]
37                                [Oilers]
38                                      []
39                         [Jets[note 61]]
40                                      []
41                                      []
42                                      []
43                      [Golden , Knights]
44                                      []
45                                      []
46                                      []
47                            [Hurricanes]
48                                      []
49                                      []
50                                      []
Name: NHL, dtype: object

In [131]:
nhl_df2018['team_lastword']=nhl_df2018.team.str.strip('*').str.split(' ').str[-1]

<ipython-input-131-e1ff4a3fadc2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nhl_df2018['team_lastword']=nhl_df2018.team.str.strip('*').str.split(' ').str[-1]

In [137]:
nhl_df2018.head()

,team,GP,W,L,OL,PTS,PTS%,GF,GA,SRS,SOS,RPt%,ROW,year,League,team_lastword
0,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,2018,NHL,Division
1,Tampa Bay Lightning*,82,54,23,5,113,.689,296,236,0.66,-0.07,.634,48,2018,NHL,Lightning
2,Boston Bruins*,82,50,20,12,112,.683,270,214,0.62,-0.07,.610,47,2018,NHL,Bruins
3,Toronto Maple Leafs*,82,49,26,7,105,.640,277,232,0.49,-0.06,.567,42,2018,NHL,Leafs
4,Florida Panthers,82,44,30,8,96,.585,248,246,-0.01,-0.04,.537,41,2018,NHL,Panthers